image: golang:alpine

stages:
    - build

compile:
    stage: build
    script:
        - apk --no-cache add git
        - mkdir -p /go/src/gitlab.com/gitlab-org
        - ln -s `pwd` /go/src/gitlab.com/gitlab-org/docker-distribution-pruner
        - cd /go/src/gitlab.com/gitlab-org/docker-distribution-pruner
        - export GOARCH=amd64
        - export CGO_ENABLED=0
        - GOOS=linux go get
        - GOOS=linux go build -ldflags "-s -w"
        - chmod +x docker-distribution-pruner
    artifacts:
        paths:
            - docker-distribution-pruner
