image: golang:latest

before_script:
    - ln -s /builds /go/src/gitlab.com/gitlab-org/docker-distribution-pruner
    - cd /go/src/gitlab.com/gitlab-org/docker-distribution-pruner

stages:
    - build

compile:
    stage: build
    script:
        - GOOS=linux go get
        - GOOS=linux go build -ldflags "-s -w"
        - GOOS=windows go get
        - GOOS=windows go build -ldflags "-s -w"
    artifacts:
        paths:
            - docker-distribution-pruner
            - docker-distribution-pruner.exe
