version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: examples/registry
  delete:
    enabled: true
http:
  addr: :5000
  secret: "shared-registry-secret"
  headers:
      X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
