---
name: build
'on':
  push:
    branches:
      - 'main'
      - 'release/*'
    tags:
      - 'v*'
  pull_request:

env:
  GOARCH: amd64
  CGO_ENABLED: 0
  GOOS: linux

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.20", "1.21", "1.22"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v -ldflags "-s -w" ./cmds/docker-distribution-pruner

      - name: Test
        run: go test ./...

      - name: static-analysis
        run: _support/go-fmt-check.sh
